// Payload terjemahan English Maulid Diba'i (443 terisi, 1 sengaja kosong:
// S11 unit 52 اَلْفَاتِحَة — keputusan Juple 2026-10-03).
// Dipakai route sementara /api/admin/fill-diba-english; file ini DIHAPUS
// bersama route-nya setelah pengisian production terverifikasi.
export const DIBA_ENGLISH: string[][] = [
 [
  "O my Lord, send blessings upon Muhammad; O my Lord, send blessings upon the Prophet and greet him with peace.",
  "O my Lord, grant him the Wasilah (the highest station in Paradise); O my Lord, single him out with virtue.",
  "O my Lord, be pleased with the Companions; O my Lord, be pleased with the descendants.",
  "O my Lord, be pleased with the teachers; O my Lord, have mercy on our parents.",
  "O my Lord, have mercy on all of us; O my Lord, have mercy on every Muslim.",
  "O my Lord, forgive everyone who has sinned; O my Lord, do not cut off our hope.",
  "O my Lord, O Hearer of our prayers; O my Lord, let us arrive to visit him.",
  "O my Lord, envelop us in his light; O my Lord, grant us Your protection and Your safety.",
  "O my Lord, place us in Your Paradise; O my Lord, save us from Your punishment.",
  "O my Lord, grant us martyrdom; O my Lord, envelop us in happiness.",
  "O my Lord, set right everyone who does good; O my Lord, shield us from everyone who harms.",
  "O my Lord, let our end be with the one whose intercession is accepted; O my Lord, send blessings upon him and greet him with peace."
 ],
 [
  "Indeed, We have granted you, O Muhammad, a clear conquest,",
  "that Allah may forgive you your sins of the past and of the future,",
  "and complete His favor upon you, and guide you to a straight path,",
  "and that Allah may aid you with a mighty victory.",
  "There has certainly come to you a Messenger from among yourselves. Grievous to him is what you suffer; he is concerned over you, and to the believers he is kind and merciful.",
  "But if they turn away, then say: Allah is sufficient for me; there is no god but He. In Him I put my trust, and He is the Lord of the Great Throne.",
  "Indeed, Allah and His angels send blessings upon the Prophet. O you who believe, send blessings upon him and greet him with a fitting greeting of peace."
 ],
 [
  "O Messenger of Allah, peace be upon you; O you of exalted standing and rank.",
  "Turn kindly toward us, O neighbor of the Banner; O folk of generosity and nobility.",
  "We are neighbors in this sanctuary — a sanctuary of kindness and goodness.",
  "We are of a people who dwelled in it, and through it they were safe from their fears.",
  "And they were watched over through the verses of the Qur'an — so be gentle with us, O brother of frailty.",
  "We know al-Batha and it knows us; as-Safa and the House are fond of us.",
  "Ours are al-Ma'la and the Khayf of Mina — know this well, and be firm upon it.",
  "The best of mankind is a father to us, and Ali al-Murtada is our noble lineage.",
  "And to the two grandsons we trace our descent — a lineage in which there is no impurity.",
  "How many imams succeeded him after him — masters by whom they were known as sayyids.",
  "By this description they were truly described, from the earliest of ages and times.",
  "Like Ali Zayn al-Abidin, and his son al-Baqir, the best of guardians.",
  "And Imam as-Sadiq, the ever-devoted, and Ali, possessor of exalted certainty.",
  "They are the people who were guided, and by the grace of Allah they were truly blessed.",
  "They turned to none but Allah, and they remained closely bound to the Qur'an.",
  "The family of the Chosen One are pure; they are the safety of the earth — so remember.",
  "They were likened to the radiant stars, just as has come in the Sunnah.",
  "And a ship of salvation, when you fear the flood of every harm.",
  "So be saved aboard it — do not be otherwise — and hold fast to Allah and seek His help.",
  "O Lord, benefit us through their blessing, and guide us to goodness through their sanctity.",
  "And let us die upon their path, in safety from all trials."
 ],
 [
  "All praise belongs to Allah, the Strong, the Prevailing,",
  "the Protector, the Seeker.",
  "The Resurrector, the Inheritor, the Bestower, the Depriver.",
  "Knower of what exists, what is manifest, what vanishes, and what passes away.",
  "Him glorify the sinking, the declining, the rising, and the setting.",
  "And Him declare One the speaking, the silent, the solid, and the melting.",
  "By His justice the still one is set in motion, and by His grace the moving one comes to rest.",
  "There is no god but Allah.",
  "The Wise, who displayed the marvels of His wisdom and its wonders",
  "in the ordering of the composition of these human forms.",
  "He created brain and bone and limb and veins and flesh and skin and hair, in a harmoniously woven arrangement,",
  "from a gushing fluid, emerging from between the backbone and the ribs.",
  "There is no god but Allah.",
  "The Generous, who spread out for His creatures the carpet of His generosity and His gifts.",
  "He descends every night to the heaven of this world and calls: Is there anyone seeking forgiveness? Is there anyone repenting?",
  "Is there anyone asking for a need, that I may grant him what he seeks?",
  "If only you could see the servants standing upon their feet, pouring forth streaming tears,",
  "and the people between remorseful and repentant,",
  "and the fearful one, reproaching his own soul,",
  "and the fugitive from sins, fleeing to Him;",
  "and they do not cease in seeking forgiveness until the palm of day restrains the trailing skirts of the darkness.",
  "Then they return having attained what they sought and reached the pleasure of the Beloved, and not one person of that company returns bearing loss.",
  "There is no god but Allah.",
  "Glory be to Him, and exalted is He — a King who brought into being the light of His Prophet Muhammad, may Allah bless him and grant him peace, from His own light, before He created Adam from clay.",
  "And He displayed his glory before all things and said: This is the master of the prophets, the greatest of the chosen, and the noblest of beloveds."
 ],
 [
  "It was said: He is Adam. He replied: Adam — through him I shall grant him the highest ranks.",
  "It was said: He is Noah. He replied: Noah — through him he shall be saved from the drowning, while those of his family and kin who opposed him shall perish.",
  "It was said: He is Abraham. He replied: Abraham — through him his proof shall stand firm against the worshippers of idols and stars.",
  "It was said: He is Moses. He replied: Moses is his brother, but this one is the Beloved; Moses is the one spoken to directly.",
  "It was said: He is Jesus. He replied: Jesus gives glad tidings of him, and he stands before his prophethood like a chamberlain.",
  "It was said: Then who is this noble Beloved, whom You have clothed with the robe of reverence,",
  "and crowned with crowns of awe and glory,",
  "and unfurled the banners above his head?",
  "He said: He is a Prophet whom I brought forth from Lu'ayy ibn Ghalib,",
  "whose father and mother shall die, and whom his grandfather shall care for, then his compassionate full uncle, Abu Talib."
 ],
 [
  "He shall be sent forth from Tihamah,",
  "just before the Day of Resurrection.",
  "Upon his back is a mark.",
  "The clouds shade him.",
  "The rain-clouds obey him.",
  "His forehead is like the dawn, his locks like the night.",
  "His nose is like an alif, his mouth like a mim, his brow like a nun.",
  "His hearing hears the scratching of the Pen; his sight pierces through the seven levels.",
  "Both his feet were kissed by the camel, and they removed what it complained of — trials and calamities.",
  "The mastigure believed in him; the trees greeted him; the stones addressed him.",
  "And the palm trunk yearned for him with the yearning of a grieving lamenter.",
  "His two hands — their blessing appeared in food and in drink.",
  "His heart neither neglects nor sleeps, but remains forever watchful in service.",
  "If he is harmed, he forgives and does not retaliate.",
  "And if he is argued with, he keeps silent and does not answer back.",
  "I shall raise him to the noblest of stations,",
  "in an ascent befitting no rider before him and none after him,",
  "in a procession of angels that surpasses all other processions.",
  "And when he ascends above the two worlds,",
  "and parts from all creation,",
  "and arrives at the distance of two bow-lengths,",
  "I am for him the intimate Companion and the One who speaks to him.",
  "Then I shall return him from the Throne,",
  "before the bed has grown cold,",
  "having attained every desire.",
  "And when the soil of Taybah is honored by him — the noblest of forms —",
  "the souls of the lovers hasten toward it, on foot and on noble mounts.",
  "May Allah's blessings, as long as the stars appear, be upon Ahmad, the best of those who rode noble camels.",
  "When the driver of the night journey sings the names of the beloveds, gratitude shakes the flanks of the riding camels.",
  "Have you not seen her, stretching out her stride, while from her tears rain-clouds pour down?",
  "And she leans toward the sanctuary in delight, and yearns for those landmarks and playing grounds.",
  "So leave the tug of the reins and do not drive her, for the pull of her longing toward the encampment is what draws her.",
  "So be rapt in joy as she is rapt — otherwise, you are a liar on the path of love.",
  "But this — this is al-'Aqiq appearing; and these are the domes of the encampment gleaming, and the tents.",
  "And that is the Green Dome, and within it is a Prophet whose light dispels the darknesses.",
  "And approval has been made true, and meeting has drawn near, and joy has come from every side.",
  "So say to the soul: Take your delight — for today there is no veil before the Beloved.",
  "Take your full delight in the Beloved with every purpose, for joy has been attained and its opposite is gone.",
  "The Prophet of Allah, the best of all creation — to him belong the highest offices and ranks.",
  "His is the lofty standing, his the heights of glory, his the everlasting honor and the noble virtues.",
  "Even if we were to journey every day upon our very eyes, and not upon noble camels,",
  "and even if we were to hold at every moment a mawlid for Ahmad, it would only be our duty.",
  "Upon him, from the All-Watching God at every moment, be blessings, as long as the light of the stars appears,",
  "encompassing the family and the Companions, all of them, entirely, and his pure progeny."
 ],
 [
  "Glory be to Him who singled him out, may Allah bless him and grant him peace, with the noblest of stations and ranks.",
  "I praise Him for the gifts He has bestowed.",
  "And I bear witness that there is no god but Allah, alone without partner, Lord of the easts and the wests.",
  "And I bear witness that our master Muhammad is His servant and His Messenger, sent to all the non-Arabs and the Arabs.",
  "May Allah bless him and grant him peace, and his family and his Companions, possessors of glorious deeds and noble ranks,",
  "with blessings and peace, everlasting and inseparable, whose reciter shall come on the Day of Resurrection undeceived.",
  "The first thing with which we open is the narration of two hadiths reported from a Prophet whose worth was immense,",
  "whose lineage was noble,",
  "and whose path was straight.",
  "He said concerning him — He who has never ceased to be All-Hearing, All-Knowing:",
  "Indeed, Allah and His angels send blessings upon the Prophet.",
  "O you who believe, send blessings upon him and greet him with peace.",
  "The first hadith is from the flowing sea of knowledge,",
  "and the speaking tongue of the Qur'an,",
  "the most singular of the scholars of mankind,",
  "our master Abdullah, son of our master al-Abbas,",
  "may Allah be pleased with them both — that the Messenger of Allah, may Allah bless him and grant him peace, said: Quraysh was a light in the presence of Allah before He created Adam, by two thousand years.",
  "That light glorified Allah, and the angels glorified because of its glorification.",
  "And when Allah created Adam, He deposited that light within his clay.",
  "He said, may Allah bless him and grant him peace: Then Allah, Mighty and Majestic is He, sent me down to the earth in the loins of Adam,",
  "and carried me in the Ark, in the loins of Noah,",
  "and placed me in the loins of Abraham the Friend, when he was cast into the fire.",
  "And Allah, Mighty and Majestic, never ceased transferring me from pure loins",
  "to pure and noble wombs,",
  "until Allah brought me forth from between my two parents — and they never once met in fornication.",
  "The second hadith is from 'Ata' ibn Yasar,",
  "from Ka'b al-Ahbar.",
  "He said: My father taught me the Torah, except for one scroll, which he used to seal and place in a chest.",
  "When my father died, I opened it, and there in it was a Prophet who shall appear at the end of time:",
  "his birth shall be in Makkah,",
  "and his migration to Madinah,",
  "and his dominion in Syria.",
  "He shall trim his hair, and he wears a wrap at his waist.",
  "He shall be the best of prophets, and his community the best of communities.",
  "They shall magnify Allah the Exalted upon every eminence.",
  "They shall form rows in prayer as they form their rows in battle.",
  "Their hearts are their scriptures; they praise Allah the Exalted in every hardship and ease.",
  "A third of them shall enter Paradise without reckoning.",
  "And a third shall come with their sins and their errors, and Allah shall forgive them.",
  "And a third shall come with great sins and errors.",
  "Then Allah the Exalted shall say to the angels: Go and weigh them. And they shall say: Our Lord, we found them to have exceeded all bounds, and we found their evil deeds like mountains —",
  "except that they bear witness that there is no god but Allah,",
  "and that Muhammad is the Messenger of Allah, may Allah bless him and grant him peace.",
  "Then the Truth shall say: By My might and My majesty,",
  "I shall not make the one who was sincere to Me in the testimony like the one who denied Me.",
  "Admit them into Paradise by My mercy.",
  "O most precious jewel of the necklaces,",
  "and essence of the elixir of the secret of existence,",
  "your praiser falls short, even if he comes bringing his utmost effort.",
  "And your describer is incapable of encompassing what you contain of the qualities of generosity and bounty.",
  "The universe is a sign, and you are the intended one.",
  "O noblest of those who attained the Praised Station,",
  "and messengers came before you, yet in loftiness and elevation they are witnesses to you.",
  "Bring present your hearts, O company of those possessed of minds,",
  "that I may unveil for you the brides of the meanings of the greatest of beloveds,",
  "singled out with the noblest of titles,",
  "who ascended into the presence of the King, the All-Bestowing,",
  "until he gazed upon His beauty without covering and without veil.",
  "And when the time came for the sun of the Message to appear",
  "in the heaven of majesty,",
  "forth came with it the decree of the Majestic One,",
  "to the chamberlain of the kingdom, Gabriel:",
  "O Gabriel, call out among all creatures,",
  "from the people of the earth and the heavens,",
  "with congratulations and glad tidings.",
  "For the guarded Light",
  "and the hidden Secret,",
  "which I brought into being before the existence of things,",
  "and before the creation of the earth and the heaven —",
  "I transfer him on this night into the womb of his mother, in joy.",
  "I fill the universe with light because of him,",
  "and I shall care for him as an orphan, and I shall purify him and the people of his household with a thorough purification.",
  "Then the Throne shook with delight and rejoicing,",
  "and the Footstool increased in awe and dignity,",
  "and the heavens were filled with lights,",
  "and the angels resounded with declarations of His oneness, glorification, and seeking forgiveness.",
  "And his mother did not cease to behold the varieties of his glory and his excellence,",
  "until the end of the completion of her pregnancy.",
  "And when the pangs of labor grew intense upon her,",
  "by the permission of the Lord of creation,",
  "she gave birth to the Beloved, may Allah bless him and grant him peace,",
  "prostrating, grateful, praising — as though he were the full moon in its completeness."
 ],
 [
  "O Prophet, peace be upon you; O Messenger, peace be upon you.",
  "O Beloved, peace be upon you; the blessings of Allah be upon you.",
  "The full moon has risen over us, and because of it the other full moons disappeared.",
  "We have never seen the like of your beauty, ever, O face of joy.",
  "You are a sun, you are a full moon; you are light upon light.",
  "You are an elixir and most precious; you are the lamp of the breasts.",
  "O my beloved, O Muhammad, O bridegroom of the two horizons.",
  "O divinely aided one, O glorified one, O Imam of the two Qiblahs.",
  "Whoever sees your face is made happy, O noble of both parents.",
  "Your pure and cool Pool is our watering place on the Day of Resurrection.",
  "We never saw the riding camels yearn through the night journey except toward you.",
  "And the clouds gave you shade, and the multitudes sent blessings upon you.",
  "And the trunk came to you weeping, and humbled itself before you.",
  "And the swift gazelle sought refuge with you, O my beloved.",
  "When they fastened the camel-litters and called out for departure,",
  "I came to them while my tears were flowing, and said: Halt for me, O guide,",
  "and carry for me these letters, O abundant longing,",
  "toward those abodes, in the evening and in the morning.",
  "Everyone in the universe is enraptured by you, O radiant of brow.",
  "And they hold for you passion, and longing, and yearning.",
  "In your meanings mankind stands scattered, bewildered.",
  "You are the Seal of the Messengers; you are ever-grateful to the Lord.",
  "Your destitute servant hopes for Your abundant, overflowing grace.",
  "In You I have placed my best hopes, O bearer of glad tidings, O warner.",
  "So aid me and grant me refuge, O Rescuer from the Blaze.",
  "O my Help, O my Refuge in the weightiest of matters.",
  "Fortunate is a servant who has taken his delight, and sorrow has lifted from him.",
  "In you, O full moon, it has shone forth; yours is the beautiful attribute.",
  "There is no origin purer than yours, ever, O grandfather of al-Husayn.",
  "So may Allah bless you, always, throughout the ages.",
  "O Guardian of good deeds, O Exalted in degrees.",
  "Expiate from me my sins, and forgive me my evil deeds.",
  "You are the Forgiver of errors, and of ruinous sins.",
  "You are the Concealer of faults, and the Pardoner of slips.",
  "Knower of the secret and of what is yet more hidden, Answerer of prayers.",
  "My Lord, have mercy on us all, and erase from us the evil deeds.",
  "May Allah bless Muhammad, as many as the lines that are written.",
  "Ahmad the guide, Muhammad, possessor of the luminous face.",
  "My Lord, have mercy on us all, through all righteous deeds."
 ],
 [
  "And he was born, may Allah bless him and grant him peace, circumcised by the hand of divine care,",
  "his eyes lined with the kohl of guidance.",
  "So the horizon shone with his splendor,",
  "and the universe glittered and gleamed with his light.",
  "And there entered into the covenant of allegiance to him those of creation who remained, just as those who had passed before entered into it.",
  "The first of the virtues of the miracles appeared",
  "in the extinguishing of the fire of Persia and the collapse of the balconies.",
  "And the devils were pelted from the heaven with burning meteors,",
  "and every tyrant among the jinn returned, humbled and subdued before the might of his sovereignty,",
  "when the radiant light blazed forth from his brilliance,",
  "and the gleaming light shone from his splendor,",
  "until he was offered to the wet-nurses.",
  "It was said: Who will take charge of this orphan pearl,",
  "for which no price can be found?",
  "The birds said: We shall take charge of him, and we shall seize his great aspiration.",
  "The wild beasts said: We have greater right to that, so that we may attain his honor and his exaltation.",
  "It was said: O assemblies of nations, be still, for Allah has decreed in His eternal wisdom",
  "that His Prophet Muhammad, may Allah bless him and grant him peace, would be nursed by Halimah.",
  "Then the wet-nurses of mankind turned away from him, because of what had preceded within the folds of the unseen —",
  "of felicity destined for Halimah bint Abi Dhu'ayb.",
  "And when her gaze fell upon him,",
  "she rushed swiftly toward him,",
  "and placed him in her lap,",
  "and embraced him to her chest.",
  "Then he beamed at her, smiling,",
  "and from his mouth came forth a light that reached the heaven.",
  "So she carried him to her mount,",
  "and set out with him to her family.",
  "And when she arrived with him at her dwelling,",
  "she witnessed his blessing upon her sheep,",
  "and every day she would see from him a proof,",
  "and his rank and stature kept rising.",
  "Until he was enfolded in the garment of gentleness and safety,",
  "and he entered among his brothers, together with the children.",
  "Then one day, while he was far from the settlements,",
  "there came toward him three persons,",
  "as though their faces were the sun and the moon.",
  "So the children ran off in flight,",
  "and the Prophet, may Allah bless him and grant him peace, stood in wonder.",
  "Then they laid him upon the ground, gently,",
  "and split open his belly with a gentle splitting,",
  "then they brought out the heart of the master of the children of Adnan,",
  "and opened it with the knife of beneficence,",
  "and removed from it the portion of Satan,",
  "and filled it with forbearance, knowledge, certainty, and contentment,",
  "and returned it to its place; then the Beloved, may Allah bless him and grant him peace, stood upright as he was before.",
  "Then the angels said: O Beloved of the Most Merciful,",
  "if you knew the good that is intended for you,",
  "you would know the measure of your rank above the others,",
  "and you would increase in joy and happiness,",
  "and in delight and light.",
  "O Muhammad, rejoice, for the banners of your knowledge have been unfurled throughout all beings,",
  "and the creatures have exchanged glad tidings at your coming.",
  "And nothing of what Allah the Exalted created remains except that it came to your command in obedience,",
  "and listening to your word.",
  "The camel shall come to you,",
  "seeking refuge in your protection.",
  "And the mastigure and the gazelle",
  "shall both testify to your messengership.",
  "And the tree, the moon, and the wolf",
  "shall proclaim your prophethood before long.",
  "Your mount is al-Buraq,",
  "longing for your beauty.",
  "And Gabriel is the herald of your kingdom; he has proclaimed your mention throughout the horizons.",
  "And the moon is commanded, for your sake, to split.",
  "And everyone in the universe longs for your appearance,",
  "awaiting the shining of your light.",
  "While the Beloved, may Allah bless him and grant him peace, was listening attentively to those apparitions,",
  "his face radiant like the light of morning,",
  "Halimah came forward, announcing with a cry.",
  "She said: O how strange this is!",
  "Then the angels said: O Muhammad, you are no stranger;",
  "rather, you are near to Allah,",
  "and for Him you are a chosen one and a beloved.",
  "Halimah said: O how alone!",
  "Then the angels said: O Muhammad, you are not alone;",
  "rather, you are the possessor of divine support,",
  "and your intimate companion is the All-Praiseworthy, the Glorious,",
  "and your brethren — your brethren are among the angels and the people of divine unity.",
  "Halimah said: O how orphaned!",
  "Then the angels said: What a noble orphan you are before Allah —",
  "for your worth in the sight of Allah is immense.",
  "And when Halimah saw him safe from the terrors,",
  "she returned with him, joyful, to the encampment.",
  "Then she recounted his story to one of the soothsayers,",
  "and related to him what had come to pass of his affair, and what had happened.",
  "The soothsayer said to him: O son of Zamzam and the Maqam,",
  "and of the Corner and the Sacred House,",
  "did you see this in wakefulness, or in a dream?",
  "He replied: By the sanctity of the King, the All-Knowing,",
  "I beheld them face to face; I do not doubt that, nor am I mistaken.",
  "Then the soothsayer said to him: Rejoice, O boy,",
  "for you are the possessor of the banners,",
  "and your prophethood is for the prophets a lock and a seal.",
  "Upon you Gabriel descends,",
  "and upon the carpet of holiness the Majestic One shall speak with you.",
  "And who is there that could encompass what you contain of distinction?",
  "And before even a part of the description of your meaning, the tongue of the lengthy praiser falls short.",
  "And he was, may Allah bless him and grant him peace, the most beautiful of people in form and in character,",
  "and the most guiding of them toward the truth in his ways.",
  "His character was the Qur'an,",
  "and his disposition was forgiveness.",
  "He gives sincere counsel to mankind,",
  "and he makes ample room in beneficence.",
  "And he forgives the offense when it is against his own right and his own person,",
  "but when the right of Allah is neglected, no one can withstand his anger.",
  "Whoever caught sight of him suddenly was filled with awe of him.",
  "And if a destitute man invited him, he would answer him.",
  "He speaks the truth, even if it is bitter,",
  "and he harbors neither deceit nor harm toward any Muslim.",
  "Whoever looked into his face knew that it was not the face of a liar.",
  "And he was, may Allah bless him and grant him peace, neither a slanderer nor a fault-finder.",
  "When he was pleased, it was as though his face were a piece of the moon.",
  "And when he spoke to people, it was as though they were picking the sweetest of fruits from his speech.",
  "And when he smiled, he smiled with teeth like hailstones.",
  "And when he spoke, it was as though pearls were falling from that speech.",
  "And when he conversed, it was as though musk were issuing from his mouth.",
  "And when he passed along a road, it was known from his fragrance that he had passed that way.",
  "And when he sat in a gathering, his fragrance remained in it for days, even when he was absent.",
  "And the finest perfume is found from him, even though he had not perfumed himself.",
  "And when he walked among his Companions, it was as though he were the moon among the brilliant stars.",
  "And when he came forth at night, it was as though people, because of his light, were at the hour of midday.",
  "And he was, may Allah bless him and grant him peace, more generous in goodness than the freely sent wind,",
  "and he was tender toward the orphan and the widow.",
  "One of those who described him said: I have never seen anyone with black locks in a red garment more handsome than the Messenger of Allah, may Allah bless him and grant him peace.",
  "And it was said to one of them: It is as though his face were the moon.",
  "He said: Rather, it is brighter than the moon, when no cloud comes between it.",
  "Majesty had enveloped him,",
  "and perfection had reached its utmost in him.",
  "One of his describers said: I never saw, before him or after him, anyone like him.",
  "So the eloquent tongue falls incapable if it seeks to enumerate his virtues."
 ],
 [
  "Glory be to Him who singled him out, may Allah bless him and grant him peace, with the loftiest abode,",
  "and carried him by night to the distance of two bow-lengths, or nearer,",
  "and strengthened him with miracles that cannot be counted,",
  "and granted him, of the attributes of perfection, what is too glorious to be fully surveyed,",
  "and gave him five things which He had given to no one before him,",
  "and granted him speech comprehensive in meaning, so that no one has attained his excellence.",
  "And for him, in every station in His presence, there was a fitting word,",
  "and to every perfection there belongs a perfection from him.",
  "He is never turned aside in question or in answer,",
  "and his tongue never moves except in what is right.",
  "And what can possibly be said of one whom the Qur'an has described,",
  "and whose virtues the Torah, the Gospel, the Psalms, and the Furqan have proclaimed?",
  "And Allah joined together for him the vision of Him and speech with Him,",
  "and He joined His name together with his name, as a reminder of the elevation of his station.",
  "And He made him a mercy to the worlds, and a light,",
  "and He filled the hearts with joy at his birth.",
  "O perfect full moon, who possessed every perfection — what can my speech express of your loftiness?",
  "You are the one who shone in the horizon of eminence, and erased with the lights every misguidance.",
  "And through you the universe was illuminated, O emblem of guidance, with light, and bestowal, and grace.",
  "May Allah, my Lord, bless you always and forever, with the mornings and the evenings,",
  "and upon all the family and the Companions — those whom the Lord of the heights singled out with perfection."
 ],
 [
  "All praise belongs to Allah, Lord of the worlds.",
  "O Allah, send blessings and peace upon our master Muhammad, and upon his family and his Companions, all of them.",
  "May Allah make us and you among those who rightfully earn his intercession,",
  "and who hope thereby for His mercy and His compassion.",
  "O Allah, by the sanctity of this noble Prophet,",
  "and his family and his Companions, who travel upon his upright path,",
  "make us among the chosen of his community,",
  "and cover us with the skirt of his sanctity,",
  "and gather us tomorrow within his company,",
  "and employ our tongues in his praise and in his support,",
  "and keep us alive holding fast to his Sunnah and to obedience to him,",
  "and cause us to die upon love of him and adherence to his community.",
  "O Allah, admit us with him into Paradise, for he is the first to enter it,",
  "and settle us with him in its palaces,",
  "for he is the first to settle in them.",
  "And have mercy on us on the day he intercedes for the creatures, and You show mercy to them.",
  "O Allah, grant us the provision of visiting him in every year,",
  "and do not make us among those heedless of You and of him, even for the measure of a slumber.",
  "O Allah, leave no one in this gathering of ours except that You have washed away his sins with the water of repentance,",
  "and covered his faults with the mantle of forgiveness.",
  "O Allah, indeed there were with us, in this past year,",
  "brothers whom destiny prevented from reaching the like of this hour;",
  "so do not deprive them of the reward of this hour and its virtue.",
  "O Allah, have mercy on us when we become the dwellers of the graves,",
  "and grant us success in righteous deeds whose radiance endures across the ages.",
  "O Allah, make us among those who remember Your favors,",
  "and those who are grateful for Your blessings,",
  "and who, on the day of meeting You, are among those who remember.",
  "And keep us alive, occupied with obedience to You,",
  "and when You take us unto You, take us untroubled by trial,",
  "and not forsaken.",
  "And seal our end, from You, with all goodness.",
  "O Allah, suffice us against the evil of the wrongdoers,",
  "and make us among those kept safe from the tribulation of this world.",
  "O Allah, make this noble Messenger an intercessor for us,",
  "and grant us through him, on the Day of Resurrection, a lofty station.",
  "O Allah, give us to drink from the Pool of Your Prophet Muhammad, may Allah bless him and grant him peace, a wholesome drink after which we shall never thirst, ever.",
  "And gather us tomorrow beneath his banner.",
  "O Allah, forgive us through him, and our fathers, and our mothers, and our shaykhs, and our teachers,",
  "and those who hold rights over us, and whoever set this goodness flowing at this hour,",
  "and all the believing men and the believing women,",
  "and the Muslim men and the Muslim women,",
  "the living among them and the dead.",
  "Indeed, You are Generous, the Answerer of prayers,",
  "and the Fulfiller of needs,",
  "and the Forgiver of sins and errors.",
  "O Most Merciful of those who show mercy.",
  "And may Allah bless our master Muhammad, and his family and his Companions, and grant them peace.",
  "Glory be to your Lord, the Lord of might, above what they describe.",
  "And peace be upon the messengers.",
  "And all praise belongs to Allah, Lord of the worlds.",
  ""
 ]
];
