// Payload terjemahan English hasil review pipeline 2026-10-03:
// Dhiya'ul Lami' 183 unit + Simtudduror 530 unit (semua terisi penuh).
// Dipakai route sementara /api/admin/fill-english-batch; file ini DIHAPUS
// bersama route-nya setelah pengisian production terverifikasi.
export const DHIYA_ENGLISH: string[][] = [
 [
  "In the name of Allah, the Most Gracious, the Most Merciful.",
  "O Lord, send blessings upon Muhammad; O Lord, send blessings and peace upon him.",
  "O Lord, send blessings upon Muhammad, Your beloved, the intercessor whose intercession is accepted.",
  "O Lord, send blessings upon Muhammad, the highest of creation in rank and the most exalted.",
  "O Lord, send blessings upon Muhammad, the loftiest of creatures in standing and the most ample in eminence.",
  "O Lord, send blessings upon Muhammad, and lead us, O Lord, along the best of paths.",
  "O Lord, send blessings upon Muhammad, grant us well-being, and heal everyone who is in pain.",
  "O Lord, send blessings upon Muhammad, set our hearts aright, pardon us, and benefit us.",
  "O Lord, send blessings upon Muhammad, shield us from the adversary, turn him away, and repel him.",
  "O Lord, send blessings upon Muhammad; we dwell within Your fortified stronghold.",
  "O Lord, send blessings upon Muhammad; O Lord, be pleased with us with Your most exalted good pleasure.",
  "O Lord, send blessings upon Muhammad, and appoint for us a gathering place in the Gardens of Paradise.",
  "O Lord, send blessings upon Muhammad; make us companions of the best of all Your creation.",
  "O Lord, send blessings upon Muhammad; O Lord, send blessings and peace upon him.",
  "O Allah, send blessings and peace, and shower blessing upon him and upon his family."
 ],
 [
  "I seek refuge in Allah from Satan, the accursed.",
  "In the name of Allah, the Most Gracious, the Most Merciful.",
  "Indeed, We have given you a clear conquest, that Allah may forgive for you what preceded of your sin and what will follow, and complete His favor upon you, and guide you to a straight path, and that Allah may aid you with a mighty victory. (48:1-3)",
  "There has certainly come to you a Messenger from among yourselves. Grievous to him is what you suffer; he is concerned over you, and to the believers he is kind and merciful. But if they turn away, say: Sufficient for me is Allah; there is no god except Him. On Him I have relied, and He is the Lord of the Great Throne. (9:128-129)",
  "Indeed, Allah and His angels send blessings upon the Prophet. O you who have believed, send blessings upon him and greet him with worthy greetings of peace. (33:56)"
 ],
 [
  "O Allah, send blessings and peace, and shower blessing upon him and upon his family.",
  "All praise belongs to Allah, who guided us through His chosen servant, the one who called us",
  "to Him by His permission; and indeed he called us — here we answer you, O you who guided us and led us.",
  "May Allah, your Creator, send blessings upon you, O Intercessor, through whom He singled us out and bestowed upon us,",
  "together with your pure family, the repository of your most exalted secret; they are the ships of salvation, our protection.",
  "And upon your noble Companions, the defenders of your religion; they became the emblem of loyalty to it.",
  "And upon those who followed them in sincerity, as long as the driver of love stirs the sorrows of longing.",
  "By Allah, whenever the Beloved is mentioned in the presence of a lover, he becomes intoxicated with love and filled with rapture.",
  "Where are the lovers for whom the sacrifice of souls, together with all precious things, is light?",
  "They never hear the name of Taha al-Mustafa mentioned except that they are revived by it and the tarnish of the heart is removed.",
  "Their spirits surge with longing for the meeting, and yearning, they ask their Lord for His good pleasure.",
  "Such is the state of the lovers; so listen to the life-story of the Intercessor, and sharpen your hearing.",
  "And listen to the attributes of Taha the Chosen, and bring your heart present until it is filled with passionate love.",
  "O our Lord, send blessings and peace always upon Your Beloved, who called us to You.",
  "O Allah, send blessings and peace, and shower blessing upon him and upon his family."
 ],
 [
  "O Allah, send blessings and peace, and shower blessing upon him and upon his family.",
  "Allah has informed us, for He said: A light has come to you. Glory be to Him who informed us.",
  "And the light is Taha, His servant, with whom He favored us; in His mention of him, how great is His favor upon us.",
  "He is the mercy of the Lord; reflect upon His words, 'So let them rejoice,' and become one who rejoices in him.",
  "Holding fast to the firmest handhold, and clinging for protection to the rope of Allah, He who created us.",
  "Perceive within yourself the lights of the one who, when asked, 'Since when have you been a prophet?' replied, 'While Adam was still'",
  "between the clay and the water. So awaken from heedlessness of this, and be one who is awake.",
  "And cross over to the secrets of my Lord: He never ceased transferring me among the chosen, preserved.",
  "No lineage ever split into two branches except that I was in the better of the two, until the time of my appearance came.",
  "For I am a chosen one from chosen ones, brought forth from a marriage which my God safeguarded for me.",
  "Allah purified him, protected him, and chose him; and He never created any human being like him.",
  "And with love of him, remembrance of him, support of him, and reverence for him, the Lord of the Throne has charged us.",
  "O our Lord, send blessings and peace always upon Your Beloved, who called us to You.",
  "O Allah, send blessings and peace, and shower blessing upon him and upon his family."
 ],
 [
  "O Allah, send blessings and peace, and shower blessing upon him and upon his family.",
  "And indeed Allah has spread forth his attributes in the Books, making them clear to us with full clarity.",
  "He took the covenant of the prophets: that whatever I have given you of wisdom, as a favor —",
  "then Our Messenger comes to you, you shall surely believe in him, and you shall aid him and become his supporters.",
  "They gave their peoples glad tidings of al-Mustafa — how great that is in rank and in station.",
  "For though he came last, he is the foremost; they walk beneath the banner of the one who called us.",
  "O community of Islam, I am the first intercessor, and the one whose intercession is accepted; I shall never relent,",
  "until I am called: Raise your head, ask and you shall be given, speak and your word shall be heard — the star of your glory has appeared.",
  "And the banner of praise, by Allah the Majestic, is in my hand, and I am the first to arrive at the Gardens.",
  "And I am the noblest of creation in the sight of Allah; truly Allah has bestowed upon you, from Himself, tenderness.",
  "And He will surely give you until you are pleased — exalted is the Giver, before the vastness of whose giving our minds fall short.",
  "By Allah, repeat the mention of the attributes of Muhammad, so that you may lift the tarnish from the hearts.",
  "O our Lord, send blessings and peace always upon Your Beloved, who called us to You.",
  "O Allah, send blessings and peace, and shower blessing upon him and upon his family."
 ],
 [
  "O Allah, send blessings and peace, and shower blessing upon him and upon his family.",
  "When the time of Ahmad's emergence drew near, by the leave of Him whose decree — whatever He wills — comes to pass,",
  "the trustworthy mother, Aminah bint Wahb, whose station Allah exalted, conceived him,",
  "from the father of the Chosen One, Abdullah son of Abdul Muttalib, who had beheld the clear proof.",
  "The light of Taha once flooded his face, then passed, plainly, to his guarded son.",
  "And he is the son of Hashim, the noble, the gallant, son of Abd Manaf, son of Qusayy.",
  "His father was called Hakim, and his standing rose high — how noble is that standing.",
  "Memorize the roots of al-Mustafa until you see, in the chain of his ancestry, Adnan.",
  "There, halt; and know that his lineage ascends to Ishmael, who was a helper to his father.",
  "And when Aminah conceived him, she complained of nothing of what seizes women.",
  "The gentleness of the Lord of heaven enfolded her, driving far away harm, anxiety, and sorrows.",
  "And she saw, as has been related, that through which she knew that the All-Guardian had honored all the worlds",
  "by the pure one within her womb; so she rejoiced, and when labor drew near she was filled with good pleasure.",
  "Glory be to Allah, and all praise belongs to Allah, and there is no god but Allah, and Allah is the Greatest; there is no might and no power except through Allah, the Most High, the Most Great — at every moment, forever, as many as the number of His creatures, as much as the measure of His good pleasure, as heavy as the weight of His Throne, and as much as the ink of His words.",
  "And the lights shone forth from every direction, for the time of the birth of the Intercessor had arrived.",
  "And shortly before dawn she brought forth the sun of guidance; the Beloved appeared, honored and divinely guarded."
 ],
 [
  "May Allah send blessings upon Muhammad; may Allah send blessings and peace upon him.",
  "O Prophet, peace be upon you; O Messenger, peace be upon you.",
  "O Beloved, peace be upon you (O Messenger of Allah); the blessings of Allah be upon you.",
  "Allah brought forth the Intercessor, the possessor of the exalted rank.",
  "And light filled all directions (through the Messenger of Allah), and encompassed the entire universe, all of it.",
  "The idols of idolatry were overturned, and the edifice of idolatry cracked and fell.",
  "And the time of guidance drew near (through the Messenger of Allah), and the stronghold of disbelief trembled.",
  "Welcome, welcome and hail to you, O possessor of the most exalted rank.",
  "O Imam of the bearers of the Message (O Messenger of Allah), through whom calamities are repelled.",
  "You are the refuge at the Gathering; to you all creation flees in terror.",
  "And they call out: Do you not see (O Messenger of Allah) the dreadful horror that has befallen us?",
  "Welcome, O light of my eye (welcome); welcome, O grandfather of al-Husayn (welcome).",
  "For that you advance and prostrate (welcome), and you are called: Intercede, and your intercession shall be accepted (welcome).",
  "So may Allah bless you (welcome), as long as light appears and radiates (welcome).",
  "And through you we ask the Most Merciful (O Allah), and the God of the Throne hears (O Allah).",
  "O Lord, forgive me my sins (O Allah), through the blessing of the Guide whose intercession is accepted (O Allah).",
  "O Lord of immense favor, O Lord (O Allah), gather us together with al-Mustafa (O Allah).",
  "And through him, look upon us (O Allah), and grant us through him every hope (O Allah).",
  "And shield us from all afflictions (O Allah), repel the calamities and lift them away (O Allah).",
  "May Allah send blessings upon Muhammad; may Allah send blessings and peace upon him.",
  "And give us drink, O Lord, relieve us, with pouring rain that flows down in torrents.",
  "And seal our lives with goodness, and make beautiful our end and our return.",
  "And may the blessing of Allah envelop the one in whom all beauty is gathered,",
  "Ahmad the Pure, and his family, and the Companions, as long as radiance shines.",
  "O Allah, send blessings and peace, and shower blessing upon him and upon his family."
 ],
 [
  "O Allah, send blessings and peace, and shower blessing upon him and upon his family.",
  "The Beloved was born and at once fell prostrate before Allah, who originated us and formed us.",
  "And the care of the Lord ever encompasses Ahmad, at every moment, inwardly and outwardly.",
  "His mother nursed him, then Thuwaybah, then Halimah, whose good fortune became manifest.",
  "Thuwaybah brought the glad tidings to her master, Abu Lahab, and he set her free in joy.",
  "Our Creator did not forget his joy over al-Mustafa — and concerning this a hadith has reached us:",
  "that the punishment is lightened for him every Monday, because of his joy at the coming of the one who came to us.",
  "And that is so despite his disbelief — so what then of the joy of one whose heart is filled with faith?",
  "And Halimah saw what she saw of the blessings of Muhammad, which bewildered the minds.",
  "Her breast flowed with milk for him, whereas before, her own son had spent the night weeping, famished and hungry.",
  "But on the night the Beloved came, her child slept in abundant contentment, full and satisfied.",
  "And her she-camel flowed with milk, and her mount grew fat — and that was a wondrous affair.",
  "Her companions scarcely recognized her; and trees and stones greeted our Master.",
  "Glory be to Him who made the trees and the stones speak, greeting al-Mustafa — glory be to Allah.",
  "O our Lord, send blessings and peace always upon Your Beloved, who called us to You.",
  "O Allah, send blessings and peace, and shower blessing upon him and upon his family."
 ],
 [
  "O Allah, send blessings and peace, and shower blessing upon him and upon his family.",
  "And the Beloved grew up upon a course of life that was well-pleasing, and he never committed any disobedience.",
  "The eye of Allah watched over him — He who disciplined him with the finest discipline of a prophet, in excellence.",
  "So he grew up truthful, virtuous, chaste, possessing chivalry, trustworthiness, and a readiness to help.",
  "Possessing resolve, courage, and dignity, and virtues too many to reckon.",
  "He was called al-Amin, and among the inhabitants of heaven he is the best of the trustworthy, whom the All-Guardian kept guarded.",
  "His mother took him to visit his father in Taybah, where death had taken him.",
  "And al-Mustafa was with her, and six of his years had by then passed over him.",
  "And death came to her during her return, so Abdul Muttalib showered tenderness upon him.",
  "Two years later death came to him as well, and an uncle whose heart was filled with affection for him took him into his care.",
  "The daughter of Khuwaylid sought him in marriage in his twenty-fifth year, and she attained glory through the Intercessor.",
  "The Lord realized her hopes for her; she obtained a lofty peace and station.",
  "And he resolved the problem of the setting of the Black Stone in the Kaaba, and in that there became manifest",
  "the breadth of his intellect and the keenness of his mind — glory be to Him who taught him and aided him.",
  "O our Lord, send blessings and peace always upon Your Beloved, who called us to You.",
  "O Allah, send blessings and peace, and shower blessing upon him and upon his family."
 ],
 [
  "O Allah, send blessings and peace, and shower blessing upon him and upon his family.",
  "Gabriel came to him with the revelation of Allah, while he was in the cave of Hira, worshipping the Most Merciful.",
  "He embraced him three times, then released him: Read — and your Lord has taught mankind.",
  "He called in secret for three years; then there came to him the command: Proclaim openly what you are commanded, in public declaration.",
  "Harm multiplied, yet he was patient for the sake of his Lord; he was ever grateful and never slackened.",
  "Khadijah and Abu Talib died in his fiftieth year, and then the harms intensified in all their forms.",
  "He came to Thaqif as a caller, but they pelted him with stones — indeed, they incited the children against him.",
  "The angel of the mountains came and said: I shall fold the mountains over them. But he said: No — I still hope for good from their offspring.",
  "The Lord carried him by night, and the messengers prayed behind him; he beheld the Barzakh and the Gardens.",
  "The Beloved ascended to the highest heavens, and he beheld the Throne and the Footstool, O our Master.",
  "And the permission for the emigration came, to Yathrib; through him the noble land shone radiant and was beautified.",
  "He resided there for ten years, calling and striving in jihad, and his Companions were his supporters.",
  "When he came, they did not raise their voices in his presence; indeed, they did not fix their gaze upon him in scrutiny,",
  "out of esteem and reverence for the station of Muhammad, for they had recited in the Qur'an concerning his excellence.",
  "And they witnessed wonders of his character, and how many astonishing things they beheld, which bewildered the minds.",
  "Generosity and pardon and liberality and humility — and even the palm trunk yearned for him in love and tenderness.",
  "And water streamed forth from between his fingers, until the army drank and was fully quenched.",
  "By Allah, the miracles of Ahmad are truly immense; the All-Guardian has raised the Prophet's station high.",
  "And he took part in twenty-seven expeditions together with the Companions, men who marched on foot and riding.",
  "How noble is he, and his Companions, and those who followed them — O Lord, join us with them, in Your beneficence.",
  "O our Lord, send blessings and peace always upon Your Beloved, who called us to You.",
  "O Allah, send blessings and peace, and shower blessing upon him and upon his family."
 ],
 [
  "O Allah, send blessings and peace upon our master Muhammad among the first generations; send blessings and peace upon our master Muhammad among the later generations; send blessings and peace upon our master Muhammad among the prophets; send blessings and peace upon our master Muhammad among the messengers; send blessings and peace upon our master Muhammad among the highest assembly until the Day of Recompense; and send blessings and peace upon our master Muhammad and upon all his family and his Companions.",
  "And I have only been able to gesture toward the attributes of the one whose qualities revive the hearts and stir the pangs of longing.",
  "Allah Himself has praised him, so no words of ours can equal it, nor can our praise ever match it.",
  "But the love residing within our innermost hearts has driven us to praise the chosen one of our Lord, who guided us.",
  "And since we have been united in love in this place, we raise the hands of our poverty and our hope",
  "to the One, the Unique, the Most High, our God, seeking access through the one who called us to Him —",
  "His chosen one, His beloved, and His elect, the adornment of all existence, through whom Allah has favored us.",
  "O our Lord, O our Lord, O our Lord — through al-Mustafa, accept us and answer our supplication.",
  "You are ours, You are ours, O treasure of our hope, in this world of ours and in our hereafter.",
  "Set right our condition and forgive our sins, and do not take us to task, O my Lord, if we have erred.",
  "Lead us upon the path of Taha al-Mustafa; make firm our steps upon the footsteps of the Beloved.",
  "Show us, by a grace from You, the countenance of Ahmad in splendor, while the eye of Your good pleasure watches over us.",
  "And bind our rope to him in every circumstance, and the ropes of those who love us and stand loyal to us,",
  "and the doers of good, and those who answered our call, and those who hold rights over us, and whoever entrusted us with a request for prayer.",
  "And all who are present, and those who strive to gather our assembly — here we are before You, and You behold us.",
  "We have indeed placed our hope in You, so fulfill our request, and hear, by Your grace, O All-Hearing One, our supplication.",
  "And aid through us the Sunnah of Taha throughout the regions of the earth, and subdue everyone who is hostile to us.",
  "And look upon us, and give us to drink of the cup of bliss; heal and swiftly restore to health those among us who are sick.",
  "And fulfill our needs for us, and make beautiful our ending at the time of death, and set right our final outcome.",
  "O Lord, gather us, together with loved ones of ours, in Your abode of al-Firdaws, O our only Hope.",
  "Through al-Mustafa, send blessings upon him and his family, as long as the morning breeze stirs the branches.",
  "Exalted is your Lord, the Lord of might, above what they describe. And peace be upon the messengers. And all praise belongs to Allah, Lord of the worlds. (37:180-182)",
  "Indeed, Allah and His angels send blessings upon the Prophet. O you who have believed, send blessings upon him and greet him with worthy greetings of peace. (33:56)",
  "Blessings and peace be upon you, O master of the messengers. Blessings and peace be upon you, O seal of the prophets. Blessings and peace be upon you, O you whom Allah sent as a mercy to the worlds. May Allah the Most High be pleased with all the Companions of the Messenger of Allah. Amin.",
  "Al-Fatihah."
 ]
];
export const SIMTU_ENGLISH: string[][] = [
 [
  "O my Lord, send blessings upon Muhammad, the noblest full moon in the universe, who has risen in radiance.",
  "O my Lord, send blessings upon Muhammad, the noblest of callers, who calls to the Truth.",
  "O my Lord, send blessings upon Muhammad, the Chosen, the truthful, the one who is believed.",
  "O my Lord, send blessings upon Muhammad, the sweetest of creation in speech, and the most truthful.",
  "O my Lord, send blessings upon Muhammad, the best of those who have realized God-consciousness.",
  "O my Lord, send blessings upon Muhammad, who was endowed with generosity and loyalty.",
  "O my Lord, send blessings upon Muhammad, and gather together what of our company has been scattered.",
  "O my Lord, send blessings upon Muhammad, and set right, and make easy, what has become tangled.",
  "O my Lord, send blessings upon Muhammad, and open every good that has been locked shut.",
  "O my Lord, send blessings upon Muhammad, and his family, and whoever is devoted to the Prophet.",
  "O my Lord, send blessings upon Muhammad, and his family, and whoever loves the Beloved with ardent love.",
  "O my Lord, send blessings upon Muhammad, and whoever holds fast to the rope of the Prophet.",
  "O my Lord, send blessings upon Muhammad; O my Lord, send blessings and peace upon him.",
  "O Allah, send the noblest of blessings and peace upon our master and our prophet Muhammad, the Most Compassionate, the Most Merciful."
 ],
 [
  "All praise belongs to Allah, firm is His dominion,",
  "clear is His proof,",
  "spread out through all existence are His generosity and His beneficence.",
  "Exalted is His glory, and immense is His majesty.",
  "He created creation for a wisdom,",
  "and He folded His knowledge over it.",
  "And He spread out for them, from the overflowing of His grace, that which the apportionment decreed within His measures.",
  "So He sent to them the noblest of His creation and the most majestic of His servants, as a mercy.",
  "His eternal will became attached to the creation of this beloved servant,",
  "so the traces of his nobility spread through the worlds of the witnessed and the unseen.",
  "How immense is this favor that the All-Bountiful has graciously bestowed,",
  "and how mighty is this grace that issued from the presence of beneficence:",
  "a perfect form that appeared within a praiseworthy frame;",
  "by its presence the corners of existence were perfumed,",
  "and it embroidered the mantle of the worlds with the embroidery of honor.",
  "O Allah, send the noblest of blessings and peace upon our master and our prophet Muhammad, the Most Compassionate, the Most Merciful."
 ],
 [
  "The Truth manifested Himself in the vast world of His holiness,",
  "with a manifestation that ordained the spreading of His grace to the near and the far.",
  "So to Him belongs the praise whose instances cannot be encompassed by any counting,",
  "and whose repetition is never wearied, however much it is repeated.",
  "When He brought forth from the world of possibility",
  "the form of this human being,",
  "so that the two weighty races might be honored by his presence,",
  "and his secrets might spread through the universes.",
  "Thus no secret has ever reached the heart of one who turns in devotion",
  "except from the overflowing grace of Allah upon this Beloved.",
  "O what a heart, whose joy flows on unceasingly, because of a Beloved whose giving embraces all mankind.",
  "Majestic is He who honored existence with a light that flooded the universe with delight and beauty.",
  "It ascended in beauty to the highest station, and attained its utmost limit in its glory, and rose exalted.",
  "The eyes beheld, in what they gazed upon, a perfect human being who removes misguidance,",
  "though he is beyond the knowledge of all the eyes have seen, in the eminence of his affairs and his perfection.",
  "Glory be to Him who brought forth from the presence of gracious favor",
  "that which the tongue is incapable of describing,",
  "and in grasping whose meanings the heart is bewildered.",
  "There spread from him into the world of the hidden and the manifest",
  "that which filled created existence with light.",
  "Blessed be Allah, a most generous God,",
  "whose verses in the Wise Remembrance gave us glad tidings with His word:",
  "There has come to you a Messenger from among yourselves; grievous to him is what you suffer; he is deeply concerned over you; to the believers he is kind and merciful.",
  "So whoever is overtaken by this glad tidings and receives it with a sound heart,",
  "has indeed been guided to a straight path.",
  "O Allah, send the noblest of blessings and peace upon our master and our prophet Muhammad, the Most Compassionate, the Most Merciful."
 ],
 [
  "And I bear witness that there is no god but Allah, alone, with no partner for Him — a testimony by which the tongue gives voice",
  "to what the heart contains",
  "of affirmation of it and submission;",
  "a testimony by which the foundations of faith stand firm in the breasts,",
  "and by which the signs of that submission and affirmation shine forth upon the people of certainty, from its secret.",
  "And I bear witness that our master Muhammad is the servant who is truthful in his speech and his action,",
  "and the conveyor from Allah of what He commanded him to convey to His creation, of His obligations and His voluntary devotions.",
  "A servant whom Allah sent to the worlds as a bearer of glad tidings and a warner.",
  "So he conveyed the Message,",
  "and he discharged the Trust,",
  "and Allah guided through him a great multitude of mankind.",
  "So he became, in the darkness of ignorance, a lamp and an illuminating moon for those who seek to see.",
  "How immense is this favor with which Allah has graciously favored mankind,",
  "and how vast is this blessing whose secret has spread across the sea and the land.",
  "O Allah, send blessings and peace, with the most majestic and most comprehensive of blessings and the purest and most expansive of greetings,",
  "upon this servant who fulfilled the right of servanthood,",
  "and who appeared therein in the robe of perfection,",
  "and who discharged the right of lordship in the stations of service to Allah, and turned toward Him with the utmost turning;",
  "blessings by which the spirit of the one who blesses him is joined to him,",
  "so that there spreads within his heart the light of the secret of his bond with him and his love for him,",
  "and by which he is inscribed, through the care of Allah, within his party.",
  "And upon his family and his Companions, who ascended the summit of glory through nearness to him,",
  "and who took shade in the shadows of true nobility through their affection for him and their love of him,",
  "as long as the breeze perfumes the universes by spreading their remembrance.",
  "O Allah, send the noblest of blessings and peace upon our master and our prophet Muhammad, the Most Compassionate, the Most Merciful."
 ],
 [
  "Now then: when the will of Allah, in His eternal knowledge, became attached",
  "to the appearance of the secrets of distinction for this noble human being,",
  "with precedence and with honoring,",
  "the resplendent power came into effect,",
  "with the expansive blessing and the overwhelming favor.",
  "Then the egg of formation split open",
  "in the great absolute world,",
  "unveiling a beauty witnessed by the eye,",
  "comprising the attribute of absolute perfection, and complete loveliness, and adornment.",
  "Then that blessed beauty journeyed on,",
  "within the noble loins and the wombs.",
  "And there was no loins that contained it",
  "except that the blessing of Allah was made perfect upon it.",
  "For he is the perfect full moon that travels through its mansions,",
  "so that by it the place of its settling and the place of its coming forth might be honored.",
  "And the eternal decrees ordained what they ordained, and brought forth of the secret of this light what they brought forth,",
  "and singled out by it whom they singled out.",
  "So its resting place was within the glorious loins",
  "and the noble, pure wombs,",
  "until he came forth into the world of witness as a man not like other men,",
  "and as a light whose appearance confounds the minds and dazzles.",
  "Then the resolve of the inscriber of these letters became attached",
  "to recording upon this paper what is known to him of the wonders of that noble light,",
  "even though tongues cannot render a tenth of the tenth of the attributes of that described one,",
  "to stir longing in the listeners,",
  "from among the elite of the believers,",
  "and as a comfort for those attached to this manifest light.",
  "Otherwise, how could pens ever articulate",
  "the affairs of the best of mankind?",
  "But what stirred me to set down what I have memorized of the biography of the noblest of created beings,",
  "and of the honors with which Allah honored him at his birth, of the grace that embraced all the worlds,",
  "and his banner has remained unfurled in the universe across the passing of the days and the months and the years,",
  "is the call of attachment to this noble presence,",
  "and the burning ardor of longing to hear its majestic attributes.",
  "And may Allah benefit by it the speaker and the hearer,",
  "so that the two of them enter into the intercession of this interceding Prophet,",
  "and are refreshed by the spirit of that bliss.",
  "O Allah, send the noblest of blessings and peace upon our master and our prophet Muhammad, the Most Compassionate, the Most Merciful."
 ],
 [
  "It is now time for the pen to write what the fingers have moved it to write,",
  "of what the understanding has gained from the attributes of this beloved, perfect servant,",
  "and his qualities, which are the finest of qualities.",
  "And here it is fitting that we record what has reached us concerning this Beloved, of reports,",
  "so that the pen and the paper may be honored by writing of him, and hearing and sight may roam sanctified in his gardens.",
  "It has reached us, in the well-known hadiths,",
  "that the first thing Allah created is the light deposited within this form.",
  "So the light of this Beloved is the first created thing to appear in the world,",
  "and from it existence branched forth, creation after creation, in what has come to be and what came of old.",
  "Abdurrazzaq narrated, with his chain, from Jabir ibn Abdullah al-Ansari, may Allah be pleased with him, that he said:",
  "I said: O Messenger of Allah, may my father and mother be your ransom, tell me about the first thing Allah created before all other things.",
  "He said: O Jabir, indeed Allah created, before all things, the light of your Prophet Muhammad, may Allah bless him and grant him peace, from His light.",
  "And it has been reported in the hadith of Abu Hurayrah, may Allah be pleased with him, that he said:",
  "The Messenger of Allah, may Allah bless him and grant him peace, said: I was the first of the prophets in creation and the last of them in being sent.",
  "And the narrations are many that he is the first of creation in existence, and the noblest of them in birth.",
  "And since eternal felicity",
  "has a hidden regard,",
  "it singled out whomever it willed of mankind",
  "with the perfection of distinction.",
  "It deposited this manifest light",
  "in the loins and wombs of those it honored among the worlds.",
  "So this light journeyed on from the loins of Adam, and Noah, and Abraham,",
  "until the hand of eternal knowledge delivered it",
  "to the one it singled out with honor — his noble father,",
  "Abdullah, son of Abdul Muttalib, possessor of immense worth;",
  "and his mother, who is safe amid the fears —",
  "the noble lady, Aminah.",
  "The loins of Abdullah received it and cast it into her womb,",
  "and her womb enclosed it, by the aid of Allah, guarding the right of this pearl and preserving it.",
  "So she carried him, by the care of Allah, as has been told of her, with a light carrying in which she found no heaviness,",
  "and she complained of no pain from it, nor any ailment,",
  "until month after month of her pregnancy had passed,",
  "and the time of his emergence into the witnessed world drew near, so that the streams of bounty might spread over the people of this world,",
  "and the traces of his essential glory might spread throughout it.",
  "O Allah, send the noblest of blessings and peace upon our master and our prophet Muhammad, the Most Compassionate, the Most Merciful."
 ],
 [
  "And from the moment there became attached to her this hidden pearl",
  "and guarded jewel,",
  "the whole universe, morning and evening, was in joy and delight",
  "at the nearness of the appearance of the radiance of this Lamp.",
  "And the eyes were gazing eagerly toward his coming forth,",
  "longing to gather up the jewels of his treasures.",
  "And every beast of Quraysh spoke with eloquent speech,",
  "announcing the perfection of the glad tidings.",
  "And there was no pregnant woman who conceived in that year",
  "except that she brought forth in her pregnancy a boy,",
  "from the blessings and the felicity of this Imam.",
  "And the earth and the heavens never ceased",
  "to be steeped in the perfume of joy at the meeting with the noblest of creatures,",
  "and at his coming forth from the world of concealment into the world of manifestation,",
  "after his journeying through the wombs and the loins.",
  "Then Allah displayed in existence the splendor of honoring,",
  "and spread, in the great world, the table of ennoblement and glorification,",
  "through the coming forth of this noble human being.",
  "O Allah, send the noblest of blessings and peace upon our master and our prophet Muhammad, the Most Compassionate, the Most Merciful."
 ],
 [
  "And when the time of the birth of this Beloved drew near,",
  "the heavens and the earths and all who are in them proclaimed welcome,",
  "and the rains of divine generosity poured down upon the people of existence,",
  "and the tongues of the angels resounded with glad tidings to the worlds,",
  "and the divine Power lifted the veil from this concealed one,",
  "so that his light might come forth perfected in the world of manifestation —",
  "a light surpassing every light.",
  "And the Truth carried out His decree",
  "concerning the one upon whom Allah perfected the blessing,",
  "from among the elite of the community,",
  "that there attend, at the birth, a company",
  "to comfort her felicitous presence,",
  "and to share with her in this spread table.",
  "So there attended, by the guidance of Allah, the Lady Maryam and the Lady Asiyah,",
  "and with the two of them, of the houris with wide beautiful eyes, those whom Allah apportioned of honor with the perfect apportionment.",
  "Then came the time upon whose arrival Allah had arranged the existence of this newborn;",
  "and the dawn of perfection split forth from the light, in a column;",
  "and the Praiser, the Praised One, came forth,",
  "submitting to Allah in glorification and prostration.",
  "O Allah, send the noblest of blessings and peace upon our master and our prophet Muhammad, the Most Compassionate, the Most Merciful."
 ],
 [
  "The universe shone in exultation at the existence of the Chosen One, Ahmad.",
  "And for the people of the universe there is comfort, and a joy renewed.",
  "So rejoice, O people of al-Mathani, for the nightingale of good fortune is singing.",
  "And take light from a beauty that surpassed, in loveliness, all compare.",
  "And ours is the glad tidings of a happiness everlasting, which shall never run out.",
  "For we have been given a gift that gathered everlasting pride.",
  "So to my Lord belongs every praise, too majestic to be encompassed by counting,",
  "in that He favored us with the existence of the Chosen One, the Guide, Muhammad.",
  "O Messenger of Allah, welcome! Indeed, through you we are made happy.",
  "And through his standing, O my God, bestow and convey every aim.",
  "And guide us along the path of his way, so that by it we are made happy and rightly guided.",
  "Lord, bring us, through his standing, to the best of seats in his nearness.",
  "And may the blessing of Allah envelop the noblest of messengers, Muhammad,",
  "and a peace everlasting, renewed at every moment.",
  "O Allah, send the noblest of blessings and peace upon our master and our prophet Muhammad, the Most Compassionate, the Most Merciful."
 ],
 [
  "And when he, may Allah bless him and grant him peace, came forth from his mother's womb, he came forth raising his gaze toward the heaven,",
  "gesturing by that raising that his is a nobility whose glory has risen high and ascended.",
  "And the time of the birth of the Master of the two worlds",
  "was, among the months, the month of Rabi' al-Awwal, and among the days, Monday.",
  "And the place of his birth and of his grave is within the two Sacred Sanctuaries.",
  "And it has been reported that he, may Allah bless him and grant him peace, was born circumcised, with kohl-lined eyes, and with the navel cord already severed;",
  "the hands of divine Power attended to that, because of his nobility in the sight of Allah.",
  "And with his coming forth into the world there appeared wonders",
  "which indicate that he is the noblest of created beings and the most excellent of beloveds.",
  "It has been reported from Abdurrahman ibn Awf, from his mother ash-Shaffa', may Allah be pleased with her —",
  "she said: When Aminah, may Allah be pleased with her, gave birth to the Messenger of Allah, may Allah bless him and grant him peace, he fell into my hands; then I heard a voice saying: May Allah have mercy on you — or: May your Lord have mercy on you.",
  "Ash-Shaffa' said: And because of him, what is between the east and the west was illuminated for her,",
  "until I looked upon some of the palaces of Rome.",
  "She said: Then I clothed him and laid him down, and it was not long before a darkness and a dread enveloped me;",
  "and I heard a speaker saying: Where have you taken him? He said: To the west.",
  "And that departed from me.",
  "Then the dread and the darkness and the shuddering returned to me from my left;",
  "and I heard a speaker saying: Where have you taken him? He said: To the east.",
  "She said: And that voice never left my mind until Allah sent him forth;",
  "and I was among the first of people to enter Islam.",
  "And how much the Sunnah has told of the immense miracles,",
  "and of the dazzling, clear signs,",
  "which establish the greatness of his nobility in the sight of his Lord,",
  "and that the eye of His care watches over him at every moment,",
  "and that he is the guide to the straight path.",
  "O Allah, send the noblest of blessings and peace upon our master and our prophet Muhammad, the Most Compassionate, the Most Merciful."
 ],
 [
  "Then, after the Power had decreed his appearance, may Allah bless him and grant him peace,",
  "and the flashes of his light had spread through the universes,",
  "the wet-nurses raced to nurse him,",
  "and the desires of the people of existence abounded to nurture this noble essence.",
  "So the decree went forth from the Majestic Presence,",
  "by means of the eternal precedents,",
  "that the most worthy to raise this Beloved and nurture him is the Lady Halimah.",
  "And when her eyes beheld him,",
  "and there appeared in her affair, of the secrets of divine Power, its hidden contents,",
  "there descended into her heart of joy and happiness",
  "what indicated that her share of honor with Allah is an abundant share.",
  "So she yearned over him with the yearning of mothers over their children,",
  "and she desired to nurse him, hoping to attain his blessings which have embraced all the worlds.",
  "So she requested from his noble mother",
  "that she be entrusted with his nursing, his nurture, and his upbringing, with the merciful eye.",
  "And she answered her, responding to her caller,",
  "for what she saw of her sincerity in excellent upbringing and the abundance of her motives.",
  "So she journeyed with him to her dwellings, joyful,",
  "while she was surrounded by the care of Allah and beheld by the eye of His solicitude.",
  "And she witnessed on her way, of the wondrous miracles,",
  "that which showed her that he is the noblest of creatures.",
  "She had come while her old she-camel and her she-ass were both weak,",
  "and she returned while the two of them outran the beasts of the caravan.",
  "And the old she-camel and the sheep flowed with milk,",
  "in a manner that bewildered the intellects and the minds.",
  "And he remained with her, in her nurture and her husband's, for two years,",
  "receiving of his blessings and the wonders of his miracles that which gladdens the eye,",
  "while his secrets spread through the two worlds,",
  "until there faced him the angels of distinction and honoring,",
  "with the nobility whose blessing embraced mankind, while he was pasturing the sheep.",
  "So they laid him upon the ground with a laying of honor,",
  "and they split his belly with a gentle splitting,",
  "then they removed from his heart what they removed,",
  "and they deposited within it, of the secrets of knowledge and wisdom, what they deposited.",
  "And the angels removed no harm from his breast; rather, they increased him in purity upon purity.",
  "And he was, with all that, in strength and steadfastness,",
  "contemplating, from the lines of divine Power, the dazzling signs.",
  "Then there reached his righteous, chaste wet-nurse",
  "what had befallen his noble person,",
  "and she feared for him some mishap that she dreaded,",
  "not knowing that he is watched with the perfect watchfulness of his Lord.",
  "So she returned him to his mother, unwilling to part from him,",
  "but because of what had arisen within her of sorrow of heart over him and compassion for him.",
  "And he is — praise be to Allah — within an impregnable fortress and a noble station.",
  "O Allah, send the noblest of blessings and peace upon our master and our prophet Muhammad, the Most Compassionate, the Most Merciful."
 ],
 [
  "So he grew up, may Allah bless him and grant him peace, upon the most perfect attributes,",
  "encompassed by the beautiful care of Allah and His overwhelming kindnesses.",
  "He would grow in a single day the growth of a child in a month,",
  "and there appeared upon him in his childhood, of the nobility of perfection, that which testifies for him that he is the master of the children of Adam — and no pride.",
  "And the stars of his ascendancy never ceased to rise,",
  "and all beings keep guard over his covenant and are obedient to his command.",
  "He never breathed upon a sick person except that Allah healed him,",
  "and he never turned toward rain except that his Lord sent it down.",
  "Until he reached the prime of his age,",
  "and a span had passed for him of the years of youth and middle age.",
  "Then the divine Presence came to him with that by which it singled him out in honor.",
  "So the Trustworthy Spirit descended upon him,",
  "with glad tidings from the Lord of the worlds,",
  "and the tongue of the Wise Remembrance recited unto him,",
  "bearing witness: Indeed, you receive the Qur'an from One All-Wise and All-Knowing.",
  "So the first thing that descended upon him from that Presence, of the comprehensive wisdoms,",
  "was the word of Allah the Exalted: Read, in the name of your Lord who created — created man from a clinging clot. Read, and your Lord is the Most Generous, who taught by the pen — taught man that which he did not know.",
  "How immense is this glad tidings, which the hand of beneficence conveyed",
  "from the presence of gracious favor",
  "unto this human being.",
  "And it was confirmed by the tidings: The Most Merciful — taught the Qur'an — created man — and taught him eloquence.",
  "And there is no doubt that he, may Allah bless him and grant him peace, is the human being intended by this teaching,",
  "from the presence of the Most Gracious, the Most Merciful.",
  "O Allah, send the noblest of blessings and peace upon our master and our prophet Muhammad, the Most Compassionate, the Most Merciful."
 ],
 [
  "Then, after the eloquent revelation had descended upon him, may Allah bless him and grant him peace,",
  "he bore the burdens of the call and the conveyance.",
  "So he called creation to Allah upon clear insight,",
  "and he was answered with submission by whoever possessed an illumined inner sight.",
  "It is an answer which the judgments and the decrees had preceded,",
  "honored by precedence in it were the Muhajirun and the Ansar.",
  "And Allah perfected, through the aspiration of this Beloved and his Companions, this religion,",
  "and subdued, by the force of their might, the hearts of the disbelievers and the heretics.",
  "And there appeared at his hands immense miracles,",
  "indicating that he is the noblest of the people of the earth and the heavens.",
  "Among them: the multiplying of the little, the curing of the ailing, the greeting of the stone, the obedience of the tree, the splitting of the moon, and the telling of things unseen,",
  "and the yearning of the palm trunk, which is among the breaches of ordinary custom,",
  "and other than that, of the immense signs and the strange miracles,",
  "and the testimony of the mastigure and the gazelle to his prophethood and messengership,",
  "with which Allah supported him in his messengership,",
  "and singled him out by them from among His creatures.",
  "And there preceded him, before prophethood, premonitory wonders,",
  "which are among the strongest signs of his prophethood and his messengership.",
  "And with their appearance and their spreading, the truthful among the believers were made happy by them,",
  "and the deniers among the disbelievers and the hypocrites were made wretched by them,",
  "and they were received with affirmation and submission by every possessor of a sound heart.",
  "O Allah, send the noblest of blessings and peace upon our master and our prophet Muhammad, the Most Compassionate, the Most Merciful."
 ],
 [
  "And among the honors with which Allah singled out the noblest of messengers",
  "is his ascension to the presence of Allah, the Most Benign, the Attainer;",
  "and the appearance of the dazzling signs of Allah in that ascension;",
  "and the heavens and those within them were honored by the radiance of the light of that Lamp.",
  "For the Beloved ascended, may Allah bless him and grant him peace, and with him was the Trustworthy One, Gabriel,",
  "to the presence of the Majestic King,",
  "with ennoblement and with veneration.",
  "And there was no heaven, nor its depths, except that its people hastened to meet him with welcome, honor, and glorification.",
  "And every messenger he passed gave him glad tidings of what he knew of his right with Allah and his noble station.",
  "Until he passed beyond the seven layers",
  "and arrived at the Presence of Absoluteness.",
  "There descended upon him, from the divine Presence,",
  "the overwhelming gifts of nearness,",
  "and It faced him with greetings,",
  "and honored him with abundant gifts,",
  "and bestowed upon him beautiful grants,",
  "and called out to him with noble salutations,",
  "after he had praised that Presence with the blessed greetings, the goodly prayers.",
  "O what overwhelming gifts they are,",
  "and exalted manifestations,",
  "in dazzling presences,",
  "in which the Essence testifies to the Essence,",
  "and the tender affections of mercy are received,",
  "and the overflowing outpourings,",
  "by hands of humility and submission.",
  "A rank before which hopes fall down exhausted; beyond it there is no beyond.",
  "And the Beloved comprehended, in that Presence, of its secret what he comprehended,",
  "and was joined, of its knowledge, to what he was joined.",
  "So He revealed to His servant what He revealed.",
  "The heart did not lie about what it saw.",
  "That was nothing but a grant with which the Presence of gracious favor singled out this human being,",
  "and bestowed upon him of its merciful affections that which the two weighty races cannot bear.",
  "And as for those gifts, the pen does not dare to explain their realities,",
  "and tongues cannot express their hidden subtleties,",
  "with which the Vast Presence singled out this seeing eye and this hearing ear.",
  "So let no aspirant aspire to peer into its concealed matter,",
  "or to encompass the witnessing of its light.",
  "For it is a presence too majestic for the gaze of gazers,",
  "and a rank too rare for any but the Master of the Messengers.",
  "So congratulations to the Muhammadan presence",
  "for what faced it of the gifts of the Ahadic Presence,",
  "and for its attainment of this immense station.",
  "O Allah, send the noblest of blessings and peace upon our master and our prophet Muhammad, the Most Compassionate, the Most Merciful."
 ],
 [
  "And since the hearing has been honored by the reports of this beloved Beloved,",
  "and by what he attained of honor in the worlds of the witnessed and the unseen,",
  "the resolve of the speaker has been stirred to spread abroad the beauties of the form of this Master and his character,",
  "so that the hearer may know the fair attributes with which Allah honored him,",
  "and the beautiful form with which the care of his Creator singled him out.",
  "So let the hearer receive what I dictate to him of the noble character with a heedful ear,",
  "for it will gather him, from the attributes of the Beloved, unto the highest rank.",
  "For no human being resembles this Master in his form and his character,",
  "and no one can stand, from among the secrets of the wisdom of Allah in his form and character, upon the essence or the trace.",
  "For the eternal Care",
  "stamped him upon sublime character traits,",
  "and set him upright in a beautiful, full-moon form.",
  "Indeed he was, may Allah bless him and grant him peace, of medium stature, white of color tinged with red,",
  "broad of forehead, beautiful; his hair between the full lock and the shorter cut.",
  "And his is the perfect proportion in his joints and his limbs,",
  "and the perfect uprightness in his beauties and his attributes.",
  "No human being has ever come upon the like of his character,",
  "in the beauty of his gaze, his hearing, and his speech.",
  "Allah created him upon the most beautiful form;",
  "within it all beauties are confined,",
  "and upon it they are restricted.",
  "When he spoke, he scattered, of knowledges and sciences, precious pearls.",
  "And he was given, of comprehensive speech, that which the most piercing of eloquent men are incapable of matching.",
  "The eyes take their delight in the gardens of the beauties of his loveliness,",
  "so you will find no creature in existence in his likeness.",
  "A Master whose laughter is a smile, whose walking is gentle, and whose sleep is a light slumber.",
  "There is no spring breeze but his character, and no lush garden but his dwelling.",
  "He is entirely mercy, and resolve, and determination, and dignity, and protection, and modesty.",
  "Miraculous in word and deed, noble in form and character, just and ever-giving.",
  "And when he walked, it was as if he were descending from a slope,",
  "and the swift walker would lose him, without hurrying.",
  "For he is the talisman-sealed treasure, whose door of attributes no key can come to open,",
  "and the perfect full moon, which captures the hearts when they imagine him, or when his radiance dawns for them.",
  "A Beloved at whose beauty of face the full moon is jealous; the hearts are bewildered in describing his meaning.",
  "So what can speech express of an attribute that renders the describers incapable?",
  "Or how could understanding grasp the meaning of an essence too majestic to have, in its description, any sharer or peer?",
  "His beauties are perfected: were he to gift his radiance to the full moon at its completeness, it would never be eclipsed.",
  "And despite the varied arts of his describers in describing him, time shall pass away while in him remains what has not been described.",
  "How immense is his mighty worth,",
  "and how vast is his all-embracing grace.",
  "O Allah, send the noblest of blessings and peace upon our master and our prophet Muhammad, the Most Compassionate, the Most Merciful."
 ],
 [
  "And he was endowed, may Allah bless him and grant him peace, with beauties of character",
  "such that the insides of pages are too narrow to write them down.",
  "He was, may Allah bless him and grant him peace, the best of people in character and in form,",
  "and the foremost of them in precedence toward the noble virtues,",
  "and the most ample of them in forbearance and gentleness toward the believers;",
  "kind and compassionate.",
  "He neither says nor does anything but what is good.",
  "His is the gentle character,",
  "and the wording that comprises the weighty meaning.",
  "When a poor man called him, he answered him with a hastened answer.",
  "And he is the merciful father, the tender, the compassionate, to the orphan and the widow.",
  "And with the gentleness of his character, his is the strong awefulness",
  "at which the limbs of the strong among mankind tremble.",
  "And from the spreading of his fragrance, the roads and the dwellings were perfumed;",
  "and by the aroma of his mention, the gatherings and the assemblies were made sweet.",
  "For he is, may Allah bless him and grant him peace, the gatherer of the attributes of perfection,",
  "and the singular one, in his form and his character, with the noblest distinction.",
  "So there is no character trait in creation that is praiseworthy",
  "except that it is received from the Adornment of Existence.",
  "I have summed up the description of the Beloved and his affair — and his is the eminence in his glory and his station.",
  "Attributes of might whose glory has risen high; they have seized even the star Suha by its reins.",
  "And the pen has spread itself out in recording what knowledge has yielded of the events of the birth of this noble Prophet,",
  "recounting what Allah honored this brought-near servant with, of honoring and glorification and noble character.",
  "So it is fitting for me to hold back the reins of the pens",
  "in this station,",
  "and to recite the greeting of peace",
  "upon the Master of Mankind:",
  "Peace be upon you, O Prophet, and the mercy of Allah and His blessings. (three times)",
  "And by that, the ending is made good, just as the opening was made good.",
  "So upon him be the best of blessings and peace.",
  "O Allah, send the noblest of blessings and peace upon our master and our prophet Muhammad, the Most Compassionate, the Most Merciful."
 ],
 [
  "All praise belongs to Allah, Lord of the worlds.",
  "O Allah, send blessings and peace upon our master Muhammad among the first generations.",
  "O Allah, send blessings and peace upon our master Muhammad among the last generations.",
  "O Allah, send blessings and peace upon our master Muhammad at every time and moment.",
  "O Allah, send blessings and peace upon our master Muhammad among the highest assembly, until the Day of Judgment.",
  "O Allah, send blessings and peace upon our master Muhammad, the Seal of the Prophets.",
  "O Allah, send blessings and peace upon our master Muhammad, and upon his family and his Companions, all of them.",
  "And when thought had strung the pearls of the Muhammadan attributes into necklaces,",
  "I turned to Allah, seeking a means through my master and my beloved Muhammad, may Allah bless him and grant him peace,",
  "that He make my striving herein appreciated,",
  "and my action herein praiseworthy,",
  "and that He inscribe my deed among the accepted deeds,",
  "and my turning among the sincere turnings,",
  "and the bonds that are joined.",
  "O Allah, O You toward whom hopes are turned and return triumphant,",
  "and at the door of whose might the riding beasts are unloaded, and there envelop them, from Him, the overwhelming outpourings:",
  "We turn to You by the noblest of means before You —",
  "the Master of the Messengers,",
  "Your truthful and trustworthy servant,",
  "our master Muhammad, whose message has encompassed all the worlds —",
  "that You send blessings and peace upon that perfect essence,",
  "the depository of Your trust,",
  "and the keeper of Your secret,",
  "and the bearer of the banner of Your all-embracing call,",
  "the greatest Father,",
  "beloved to You and singled out with the most splendid honor,",
  "in every station among the stations of nearness and manifestation,",
  "the distributor of Your aid among Your servants,",
  "and the cupbearer of the cups of Your guidance to the people of Your love,",
  "the Master of the two worlds,",
  "and the noblest of the two weighty races,",
  "the beloved, pure servant,",
  "singled out from You with the most majestic of distinctions.",
  "O Allah, send blessings and peace upon him, and upon his family and his Companions,",
  "and the people of the presence of his closeness, among his beloveds.",
  "O Allah, we present before You the standing of this noble Prophet,",
  "and we seek access to You through the honor of his immense station,",
  "that You watch over us in our movements and our rests with the eye of Your care,",
  "and that You guard us in all our phases",
  "and our turnings, with Your beautiful guardianship",
  "and Your impregnable protection,",
  "and that You bring us, of the honor of nearness to You and to this Beloved, to the utmost limit of our hopes,",
  "and that You accept from us what we have set in motion of our intentions and our deeds,",
  "and that You make us, in the presence of this Beloved, among those who are present,",
  "and upon the paths of following him, among the wayfarers,",
  "and of Your right and his right, among the fulfillers,",
  "and of Your covenant, among the keepers.",
  "O Allah, we have eager hopes in Your special mercy, so do not deprive us;",
  "and beautiful expectations, which are our means unto You, so do not disappoint us.",
  "We have believed in You, and in Your Messenger, and in the religion he brought.",
  "And we have turned by him toward You, seeking intercession,",
  "that You meet the sinner among us with forgiveness,",
  "and the wrongdoer with beneficence,",
  "and the asker with what he asked,",
  "and the hopeful with what he hoped for.",
  "And that You make us among those who aided this Beloved and assisted him,",
  "and befriended him and supported him.",
  "And encompass with his blessing and his noble orientation our children and our parents,",
  "and the people of our region and our valley,",
  "and all the Muslim men and Muslim women,",
  "and the believing men and believing women,",
  "in every direction.",
  "And keep the banner of the upright religion unfurled in all regions, forever (three times),",
  "and the landmarks of Islam and faith inhabited by their people,",
  "in meaning and in form.",
  "And lift, O Allah, the distress of the distressed,",
  "and discharge the debt of the indebted,",
  "and forgive the sinners,",
  "and accept the repentance of those who repent,",
  "and spread Your mercy over Your believing servants, all of them.",
  "And suffice against the evil of the transgressors and the wrongdoers,",
  "and spread justice through the upholders of truth in all districts and regions,",
  "and support them with aid from You, and victory over the obstinate among the hypocrites and the disbelievers.",
  "And place us, O our Lord, in the impregnable fortress against all afflictions (three times),",
  "and in the firm stronghold against sins and errors.",
  "And keep us steadfast in acting in obedience to You, and sincere in Your service,",
  "and when You take us unto You, take us as Muslims and believers.",
  "And seal our end, from You, with goodness — all of us.",
  "And send blessings and peace upon this beloved Beloved,",
  "for the bodies and the spirits and the hearts,",
  "and upon his family and his Companions and whoever is ascribed to him.",
  "And the last of our call is that all praise belongs to Allah, Lord of the worlds.",
  "Glory be to your Lord, the Lord of might, above what they describe; and peace be upon the messengers; and all praise belongs to Allah, Lord of the worlds.",
  "Indeed Allah and His angels send blessings upon the Prophet. O you who have believed, send blessings upon him and pronounce peace.",
  "O Allah, send blessings and peace upon him; may Allah bless him and grant him peace.",
  "Their call therein is: Glory be to You, O Allah; and their greeting therein is: Peace; and the last of their call is: All praise belongs to Allah, Lord of the worlds.",
  "Blessings and peace be upon you, O Master of the Messengers.",
  "Blessings and peace be upon you, O Seal of the Prophets.",
  "Blessings and peace be upon you, O you whom Allah sent as a mercy to the worlds.",
  "And may Allah be pleased with all the Companions of the Messenger of Allah. Amin."
 ]
];
